<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="StaffInfo.aspx.cs" Inherits="OnlinePharmacy.StaffInfo" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            text-align: center;
        }

        .auto-style2 {
            width: 100%;
        }

        .auto-style5 {
            height: 23px;
        }

        .auto-style6 {
            width: 185px;
        }

        .auto-style7 {
            height: 23px;
            width: 185px;
        }

        .auto-style8 {
            text-align: center;
            width: 185px;
        }

        .auto-style9 {
            margin-left: 0px;
        }

        .auto-style10 {
            text-align: center;
            width: 185px;
            height: 23px;
        }

        .auto-style11 {
            width: 413px;
            text-align: right;
            height: 29px;
        }

        .auto-style12 {
            text-align: center;
            width: 185px;
            height: 29px;
        }

        .auto-style13 {
            height: 29px;
        }

        .auto-style14 {
            text-align: center;
            height: 30px;
        }

        .auto-style15 {
            width: 100%;
            margin-top: 0px;
        }

        .auto-style16 {
            width: 413px;
            text-align: right;
            height: 26px;
        }

        .auto-style17 {
            width: 185px;
            height: 26px;
        }

        .auto-style18 {
            height: 26px;
        }

        .auto-style19 {
            width: 413px;
            text-align: right;
            height: 4px;
        }

        .auto-style20 {
            width: 185px;
            height: 4px;
        }

        .auto-style21 {
            height: 4px;
        }

        .auto-style22 {
            width: 413px;
            text-align: right;
        }

        .auto-style23 {
            width: 413px;
            text-align: right;
            height: 23px;
        }

        .auto-style24 {
            width: 404px;
            text-align: right;
            height: 23px;
        }

        .auto-style25 {
            width: 404px;
            text-align: right;
        }
        .auto-style26 {
            text-align: left;
        }
    </style>
</head>
<body style="background-image: url('Image/bg (6).jpg')">
    <form id="form1" runat="server">
        <div>
            <h1 class="auto-style1">ONLINE MEDICINE SHOP</h1>
            <h2 class="auto-style1">STAFF DETAILS</h2>
            <p class="auto-style26">
                <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Panel" />
            </p>
        </div>
        <asp:SqlDataSource ID="SqlDataSourceStaff" runat="server" ConnectionString="<%$ ConnectionStrings:CustomerConnectionString %>" SelectCommand="SELECT * FROM [Staff]" UpdateCommand="UPDATE [Staff] SET [Name]=@name, [Username]=@username,[Phone]=@phone,[Password]=@password WHERE [Id]=@id " DeleteCommand="DELETE FROM [Staff] WHERE [Id]=@id"></asp:SqlDataSource>
        <div class="auto-style1">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="Id" DataSourceID="SqlDataSourceStaff" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Width="830px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username" />
                    <asp:BoundField DataField="Phone" HeaderText="Phone" SortExpression="Phone" />
                    <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                </Columns>
                <FooterStyle BackColor="White" ForeColor="#000066" />
                <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                <RowStyle ForeColor="#000066" />
                <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#007DBB" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#00547E" />
            </asp:GridView>
        </div>
        <h2 class="auto-style1">ADD STAFF</h2>
        <table class="auto-style2" align="center">
            <tr>
                <td class="auto-style16">Name :</td>
                <td class="auto-style17">
                    <asp:TextBox ID="TextBoxName" runat="server" Width="180px"></asp:TextBox>
                </td>
                <td class="auto-style18"></td>
            </tr>
            <tr>
                <td class="auto-style19">Username :</td>
                <td class="auto-style20">
                    <asp:TextBox ID="TextBoxUser" runat="server" Width="180px"></asp:TextBox>
                </td>
                <td class="auto-style21"></td>
            </tr>
            <tr>
                <td class="auto-style22">Phone :</td>
                <td class="auto-style6">
                    <asp:TextBox ID="TextBoxPhone" runat="server" Width="180px"></asp:TextBox>
                </td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style16">Password :</td>
                <td class="auto-style17">
                    <asp:TextBox ID="TextBoxPass" runat="server" TextMode="Password" Width="180px"></asp:TextBox>
                </td>
                <td class="auto-style18"></td>
            </tr>
            <tr>
                <td class="auto-style22">Confirm Password :</td>
                <td class="auto-style6">
                    <asp:TextBox ID="TextBoxConfirm" runat="server" TextMode="Password" Width="180px"></asp:TextBox>
                </td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style23"></td>
                <td class="auto-style7"></td>
                <td class="auto-style5"></td>
            </tr>
            <tr>
                <td class="auto-style11"></td>
                <td class="auto-style12">
                    <asp:Button ID="ButtonAdd" runat="server" OnClick="ButtonAdd_Click" Text="ADD" Height="26px" />
                </td>
                <td class="auto-style13"></td>
            </tr>
        </table>
        <h1 class="auto-style14">DELETE STAFF</h1>
        <table class="auto-style15" align="center">
            <tr>
                <td class="auto-style24">ID :</td>
                <td class="auto-style10">
                    <asp:TextBox ID="TextBoxDelete" runat="server" CssClass="auto-style9" Width="178px"></asp:TextBox>
                </td>
                <td class="auto-style5"></td>
            </tr>
            <tr>
                <td class="auto-style25">&nbsp;</td>
                <td class="auto-style8">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style25">&nbsp;</td>
                <td class="auto-style8">
                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="DELETE" />
                </td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style25">&nbsp;</td>
                <td class="auto-style8">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </table>
    </form>
</body>
</html>
